base_url = "https://divestdtu.dk"
title = "Divest DTU"
build_search_index = true
generate_feed = true
compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "favicon.ico"
theme = "auto"      

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
    { name = "facebook", url = "https://www.facebook.com/DivestDTU", weight = 3 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/not_matthias", icon = "twitter" },
    { name = "github", url = "https=//github.com/not-matthias/", icon = "github" },
]

